name: "Publish @lukekaalim/api-models"

on:
  push:
    tags:
      - '@lukekaalim/api-models@*'

jobs:
  publish-models:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-models
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
