name: "Publish @astral-atlas/sesame-models"

on:
  push:
    tags:
      - '@astral-atlas/sesame-models@*'

jobs:
  publish-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public -w models
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
