name: "Publish Sesame Services"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'services/**'

jobs:
  publish-test-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/test
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y zip unzip curl jq

      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
      - name: Initialize
        id: init
        run: terraform init
      - name: Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          TF_LOG: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          

