name: "Publish @astral-atlas/sesame-www"

on:
  push:
    tags:
      - '@astral-atlas/sesame-www@*'

jobs:
  release-www:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build -w www
      - run: cd www/dist; zip -r ../../sesame-www.zip .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: sesame-www.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
