name: "Publish @astral-atlas/sesame-www"

on:
  workflow_dispatch:
  push:
    paths:
      - 'www/**'

jobs:
  release-www:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci install
      - run: npm run build --workspace=www
      - uses: papeloto/action-zip@v1
        with:
          files: www/artifacts/
          dest: sesame-www.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: sesame-www.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
